language: generic

services:
  - docker

install:
  - docker pull mcr.microsoft.com/powershell:6.2.3-alpine-3.8
  
script:
  # Unit Tests for PowerShell scripts
  - docker run -v ${TRAVIS_BUILD_DIR}:/tmp/src/ mcr.microsoft.com/powershell:6.2.3-alpine-3.8 pwsh -c "
      \$ProgressPreference='SilentlyContinue';
      Install-Module Pester -Force -SkipPublisherCheck -Scope CurrentUser;
      Invoke-Pester /tmp/src;
      exit $LastExitCode;"
  # Linting for PowerShell scripts
  - docker run -v ${TRAVIS_BUILD_DIR}:/tmp/src/ mcr.microsoft.com/powershell:6.2.3-alpine-3.8 pwsh -c "
      \$ProgressPreference='SilentlyContinue';
      Install-Module PSScriptAnalyzer -Force -SkipPublisherCheck -Scope CurrentUser;
      Invoke-ScriptAnalyzer -Path /tmp/src -Recurse -ReportSummary -EnableExit;
      exit $LastExitCode;"
